### PR TITLE
Fixed "new Identifier()" problem in Minecraft 1.21, is "Identifier.of…

### PR DESCRIPTION
**Pull request by XJgout**
…()" and Update to Minecraft 1.21

### CODE REVIEW

**Comment by XJgout** [comment]
Sorry I forget commit and pull build.gradle and some 1.21 files, so I closed the pr

**Comment by XJgout** [comment]
sorry it's push not pull

**Comment by MotWnb** [comment]
updated in my pr

**Comment by XJgout** [comment]
Sorry I forget commit and push build.gradle and some 1.21 files, so I closed the pr

**Pull request closed without merging**
